opam-version: "2.0"
synopsis: "Logseq chat mobile core backed by DataScript OCaml"
maintainer: "Logseq <hello@logseq.com>"
authors: "Logseq"
license: "MIT"
depends: [
  "ocaml" {>= "5.1.0"}
  "dune" {>= "3.17"}
  "datascript_ocaml"
  "datascript-ocaml-native"
  "datascript-ocaml-lg"
  "melange-edn-native"
  "melange-transit-native"
  "lg"
  "lg-test" {with-test}
  "lui"
  "signal-lg"
  "mldoc"
  "ocaml-fsrs"
  "yojson"
]
pin-depends: [
  ["datascript_ocaml.dev" "git+https://github.com/logseq/datascript-ocaml.git#b3c98542ef4e65c7a325c86c3fc6ac00f46d2d80"]
  ["datascript-ocaml-native.dev" "git+https://github.com/logseq/datascript-ocaml.git#b3c98542ef4e65c7a325c86c3fc6ac00f46d2d80"]
  ["datascript-ocaml-lg.dev" "git+https://github.com/logseq/datascript-ocaml.git#b3c98542ef4e65c7a325c86c3fc6ac00f46d2d80"]
  ["persistent_sorted_set_ocaml.dev" "git+https://github.com/logseq/persistent-sorted-set-ocaml.git#4016dae1cdf4304207d8277ff9957656cdd8b177"]
  ["melange-edn-core.0.5.0" "git+https://github.com/RCmerci/melange-edn.git#3cb79f278e972388a0a2b2ea1caec7a008a0b956"]
  ["melange-edn-native.0.5.0" "git+https://github.com/RCmerci/melange-edn.git#3cb79f278e972388a0a2b2ea1caec7a008a0b956"]
  ["melange-edn-melange.0.5.0" "git+https://github.com/RCmerci/melange-edn.git#3cb79f278e972388a0a2b2ea1caec7a008a0b956"]
  ["melange-transit-core.0.1.0" "git+https://github.com/tiensonqin/melange-transit.git#898bc1418e8e6405f53d659209d932cddc6e3070"]
  ["melange-transit-native.0.1.0" "git+https://github.com/tiensonqin/melange-transit.git#898bc1418e8e6405f53d659209d932cddc6e3070"]
  ["melange-transit-melange.0.1.0" "git+https://github.com/tiensonqin/melange-transit.git#898bc1418e8e6405f53d659209d932cddc6e3070"]
  ["lg.dev" "git+ssh://git@github.com/tiensonqin/lg.git#c4f05931ea8fe47590634bd394282afc48b417e8"]
  ["lui.0.1.0" "git+ssh://git@github.com/tiensonqin/lui.git#f5ab59355d81612cb698aa6a23ee1ce63e0633e3"]
  ["signal-lg.0.1.0" "git+https://github.com/tiensonqin/signal-lg.git#ed2e6c68322316d64bf41644480a5f8901940a02"]
  ["mldoc.dev" "git+https://github.com/logseq/mldoc.git#c51b957ccb0f9b0173bb1e0b422a6798f1a59dd2"]
  ["ocaml-fsrs.0.1.0-alpha3" "git+https://github.com/logseq/ocaml-fsrs.git#0ac7779062df50e7a9760d926ee215ed52c73194"]
]
build: [
  ["dune" "subst"] {dev}
  ["dune" "build" "-p" name "-j" jobs "@install" "@runtest" {with-test}]
]
