(library
 (name logseq_chat_core)
 (wrapped false)
 (modules
  logseq_chat_api
  logseq_chat_http
  logseq_chat_model
  logseq_chat_rpc)
 (libraries datascript-ocaml-native yojson unix)
 (foreign_stubs
  (language c)
  (names logseq_chat_https_stub)))

(executable
 (name logseq_chat_mobile_entry)
 (modules
  logseq_chat_mobile_entry
  logseq_chat_sqlite)
 (modes exe object shared_object)
 (libraries logseq_chat_core datascript-ocaml-native.sqlite threads.posix)
 (foreign_stubs
  (language c)
  (names logseq_chat_core_ffi))
 (link_flags :standard -cclib -L/opt/homebrew/opt/sqlite/lib)
 (flags :standard -linkall))

(test
 (name logseq_chat_model_test)
 (modules logseq_chat_model_test)
 (libraries logseq_chat_core))

(test
 (name logseq_chat_api_test)
 (modules logseq_chat_api_test)
 (libraries logseq_chat_core))

(test
 (name logseq_chat_http_test)
 (modules logseq_chat_http_test)
 (libraries logseq_chat_core unix))

(test
 (name logseq_chat_rpc_test)
 (modules logseq_chat_rpc_test)
 (libraries logseq_chat_core yojson))

(test
 (name logseq_chat_sqlite_test)
 (modules
  logseq_chat_sqlite_test
  logseq_chat_sqlite)
 (libraries logseq_chat_core datascript-ocaml-native.sqlite threads.posix))
