package com.logseq.chat.ui.extensions

import androidx.activity.compose.BackHandler
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Close
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TextField
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.unit.dp
import dev.lui.LuiExtensionContext
import dev.lui.LuiExtensionEventSchema
import dev.lui.LuiExtensionProperty
import dev.lui.LuiExtensionRegistry
import dev.lui.LuiExtensionValueKind

// Port of the former logseq_chat_extensions.dart — the chat-specific
// extension hosts. Fingerprints are generated by the OCaml core and must
// match byte-for-byte.
private const val EDITOR_FINGERPRINT =
    "lui-extension-v1|15:outliner-editor|profiles:android/kotlin," +
        "ios/swiftui|standard-children:0|children:|" +
        "properties:18:caret-utf16-offset:int:required:none,5:title:string:" +
        "required:none,8:block-id:string:required:none|events:11:text-change[" +
        "18:caret-utf16-offset:int:required,5:title:string:required],12:caret-change[" +
        "18:caret-utf16-offset:int:required],6:return[18:caret-utf16-offset:int:" +
        "required,5:title:string:required],9:backspace[16:selection-length:int:" +
        "required,5:title:string:required]"
private const val RICH_FINGERPRINT =
    "lui-extension-v1|22:outliner-block-content|profiles:android/kotlin," +
        "ios/swiftui|standard-children:0|children:|" +
        "properties:10:asset-type:string:required:none,10:local-path:string:" +
        "required:none,11:markup-json:string:required:none,12:is-completed:bool:" +
        "required:none,18:youtube-target-url:string:required:none,5:title:string:" +
        "required:none,8:block-id:string:required:none,8:is-asset:bool:required:none|" +
        "events:10:drag-start[4:uuid:string:required],4:drop[4:uuid:string:required," +
        "9:placement:string:required],4:edit[4:uuid:string:required],9:open-node[" +
        "4:uuid:string:required]"
private const val NAVIGATION_FINGERPRINT =
    "lui-extension-v1|23:native-navigation-stack|profiles:android/kotlin," +
        "ios/swiftui|standard-children:1|children:|" +
        "properties:26:composer-dismissal-enabled:bool:required:none," +
        "28:bottom-occupies-layout-space:bool:required:none,5:depth:int:required:none," +
        "5:title:string:required:none|events:16:dismiss-composer[],4:back[" +
        "5:count:int:required]"
private const val SEARCH_FINGERPRINT =
    "lui-extension-v1|26:native-search-presentation|profiles:android/kotlin," +
        "ios/swiftui|standard-children:1|children:|" +
        "properties:5:depth:int:required:none,5:query:string:required:none," +
        "5:title:string:required:none,9:presented:bool:required:none|events:" +
        "13:query-changed[5:query:string:required],4:back[5:count:int:required]," +
        "7:dismiss[]"

fun logseqChatExtensionRegistry(
    resolveAssetPath: (String) -> String = { it },
): LuiExtensionRegistry = LuiExtensionRegistry().apply {
    register(
        "outliner-editor",
        EDITOR_FINGERPRINT,
        properties = listOf(
            LuiExtensionProperty("caret-utf16-offset", LuiExtensionValueKind.INTEGER),
            LuiExtensionProperty("title", LuiExtensionValueKind.STRING),
            LuiExtensionProperty("block-id", LuiExtensionValueKind.STRING),
        ),
        events = listOf(
            LuiExtensionEventSchema(
                "text-change",
                listOf(
                    LuiExtensionProperty("caret-utf16-offset", LuiExtensionValueKind.INTEGER, required = true),
                    LuiExtensionProperty("title", LuiExtensionValueKind.STRING, required = true),
                ),
            ),
            LuiExtensionEventSchema(
                "caret-change",
                listOf(
                    LuiExtensionProperty("caret-utf16-offset", LuiExtensionValueKind.INTEGER, required = true),
                ),
            ),
            LuiExtensionEventSchema(
                "return",
                listOf(
                    LuiExtensionProperty("caret-utf16-offset", LuiExtensionValueKind.INTEGER, required = true),
                    LuiExtensionProperty("title", LuiExtensionValueKind.STRING, required = true),
                ),
            ),
            LuiExtensionEventSchema(
                "backspace",
                listOf(
                    LuiExtensionProperty("selection-length", LuiExtensionValueKind.INTEGER, required = true),
                    LuiExtensionProperty("caret-utf16-offset", LuiExtensionValueKind.INTEGER, required = true),
                    LuiExtensionProperty("title", LuiExtensionValueKind.STRING, required = true),
                ),
            ),
        ),
    ) {
        OutlinerEditor(this)
    }
    register(
        "outliner-block-content",
        RICH_FINGERPRINT,
        properties = listOf(
            LuiExtensionProperty("asset-type", LuiExtensionValueKind.STRING),
            LuiExtensionProperty("local-path", LuiExtensionValueKind.STRING),
            LuiExtensionProperty("markup-json", LuiExtensionValueKind.STRING),
            LuiExtensionProperty("is-completed", LuiExtensionValueKind.BOOLEAN),
            LuiExtensionProperty("youtube-target-url", LuiExtensionValueKind.STRING),
            LuiExtensionProperty("title", LuiExtensionValueKind.STRING),
            LuiExtensionProperty("block-id", LuiExtensionValueKind.STRING),
            LuiExtensionProperty("is-asset", LuiExtensionValueKind.BOOLEAN),
        ),
        events = listOf(
            LuiExtensionEventSchema(
                "drag-start",
                listOf(LuiExtensionProperty("uuid", LuiExtensionValueKind.STRING, required = true)),
            ),
            LuiExtensionEventSchema(
                "drop",
                listOf(
                    LuiExtensionProperty("uuid", LuiExtensionValueKind.STRING, required = true),
                    LuiExtensionProperty("placement", LuiExtensionValueKind.STRING, required = true),
                ),
            ),
            LuiExtensionEventSchema(
                "edit",
                listOf(LuiExtensionProperty("uuid", LuiExtensionValueKind.STRING, required = true)),
            ),
            LuiExtensionEventSchema(
                "open-node",
                listOf(LuiExtensionProperty("uuid", LuiExtensionValueKind.STRING, required = true)),
            ),
        ),
    ) {
        OutlinerBlockContent(this, resolveAssetPath)
    }
    register(
        "native-navigation-stack",
        NAVIGATION_FINGERPRINT,
        acceptsStandardChildren = true,
        properties = listOf(
            LuiExtensionProperty("composer-dismissal-enabled", LuiExtensionValueKind.BOOLEAN),
            LuiExtensionProperty("bottom-occupies-layout-space", LuiExtensionValueKind.BOOLEAN),
            LuiExtensionProperty("depth", LuiExtensionValueKind.INTEGER),
            LuiExtensionProperty("title", LuiExtensionValueKind.STRING),
        ),
        events = listOf(
            LuiExtensionEventSchema("dismiss-composer"),
            LuiExtensionEventSchema(
                "back",
                listOf(LuiExtensionProperty("count", LuiExtensionValueKind.INTEGER, required = true)),
            ),
        ),
    ) {
        NavigationBoundary(this)
    }
    register(
        "native-search-presentation",
        SEARCH_FINGERPRINT,
        acceptsStandardChildren = true,
        properties = listOf(
            LuiExtensionProperty("depth", LuiExtensionValueKind.INTEGER),
            LuiExtensionProperty("query", LuiExtensionValueKind.STRING),
            LuiExtensionProperty("title", LuiExtensionValueKind.STRING),
            LuiExtensionProperty("presented", LuiExtensionValueKind.BOOLEAN),
        ),
        events = listOf(
            LuiExtensionEventSchema(
                "query-changed",
                listOf(LuiExtensionProperty("query", LuiExtensionValueKind.STRING, required = true)),
            ),
            LuiExtensionEventSchema(
                "back",
                listOf(LuiExtensionProperty("count", LuiExtensionValueKind.INTEGER, required = true)),
            ),
            LuiExtensionEventSchema("dismiss"),
        ),
    ) {
        SearchPresentation(this)
    }
}

// Android hardware-back routing, mirroring the former PopScope semantics:
// composer dismissal takes precedence, then nav-stack back, then the
// system.
@Composable
private fun NavigationBoundary(context: LuiExtensionContext) {
    val depth = context.int("depth") ?: 0
    val dismissesComposer = context.flag("composer-dismissal-enabled")
    BackHandler(enabled = depth > 0 || dismissesComposer) {
        if (dismissesComposer) {
            context.emit("dismiss-composer")
        } else if (depth > 0) {
            context.emit("back", "count" to 1)
        }
    }
    context.Children()
}

// Modal search sheet — the core drives `query`; results are standard
// children rendered below the field.
@Composable
private fun SearchPresentation(context: LuiExtensionContext) {
    val presented = context.flag("presented")
    if (!presented) return
    val title = context.string("title") ?: ""
    val query = context.string("query") ?: ""

    BackHandler {
        context.emit("dismiss")
    }
    Surface(
        modifier = Modifier
            .fillMaxSize()
            .testTag("native-search-presentation"),
        color = MaterialTheme.colorScheme.surface,
    ) {
        Column {
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 4.dp, vertical = 4.dp),
                verticalAlignment = Alignment.CenterVertically,
            ) {
                IconButton(onClick = { context.emit("back", "count" to 1) }) {
                    Icon(
                        Icons.AutoMirrored.Filled.ArrowBack,
                        contentDescription = "Back",
                    )
                }
                var fieldValue by remember(query) { mutableStateOf(query) }
                TextField(
                    value = fieldValue,
                    onValueChange = {
                        fieldValue = it
                        context.emit("query-changed", "query" to it)
                    },
                    modifier = Modifier
                        .weight(1f)
                        .testTag("field.search"),
                    placeholder = { Text(title.ifEmpty { "Search" }) },
                    singleLine = true,
                )
                if (fieldValue.isNotEmpty()) {
                    IconButton(
                        onClick = {
                            fieldValue = ""
                            context.emit("query-changed", "query" to "")
                        },
                    ) {
                        Icon(Icons.Filled.Close, contentDescription = "Clear")
                    }
                }
            }
            Box(modifier = Modifier.fillMaxSize()) {
                context.Children()
            }
        }
    }
}
