let () =
  Alcotest.run "logseq-chat"
    [
      "asset_files", Asset_files_test.cases;
      "e2ee", E2ee_test.cases;
      "e2ee_keyring", E2ee_keyring_test.cases;
      "graph_store", Graph_store_test.cases;
      "mobile_payload", Mobile_payload_test.cases;
      "search_index", Search_index_test.cases;
      "graph_sqlite", Graph_sqlite_test.cases;
      "entity_sync", Entity_sync_test.cases;
      "http", Http_test.cases;
      "api", Api_test.cases;
      "sync_tx", Sync_tx_test.cases;
      "graph_bootstrap", Graph_bootstrap_test.cases;
      "platform_crypto", Platform_crypto_test.cases;
      "edn", Edn_test.cases;
      "fractional_order", Fractional_order_test.cases;
      "live_sync", Live_sync_test.cases;
      "lui_host_update", Lui_host_update_test.cases;
      "lui_projection", Lui_projection_test.cases;
      "lui_snapshot", Lui_snapshot_test.cases;
      "sync_protocol", Sync_protocol_test.cases;
      "markup", Markup_test.cases;
      "flashcards", Flashcards_test.cases;
      "mobile_session", Mobile_session_test.cases;
      "outliner", Outliner_test.cases;
      "snapshot", Snapshot_test.cases;
      "sync_checkpoint", Sync_checkpoint_test.cases;
      "sync_state", Sync_state_test.cases;
      "logseq_storage_codec", Logseq_storage_codec_test.cases;
      "sync_session", Sync_session_test.cases;
      "outliner_effects", Outliner_effects_test.cases;
      "e2e_seed_data", E2e_seed_data_test.cases;
      "model", Model_test.cases;
      "sqlite", Sqlite_test.cases;
      "pending_ops", Pending_ops_test.cases;
      "graph_read", Graph_read_test.cases;
      "mobile_graph", Mobile_graph_test.cases;
      "outliner_state", Outliner_state_test.cases;
      "pending_projection", Pending_projection_test.cases;
      "graph_runtime", Graph_runtime_test.cases;
      "rpc", Rpc_test.cases;
      "app", App_test.cases;
      "drive", Drive_scenario_test.cases;
      "repro", Repro_wedge_test.cases;
    ]
