(ns logseq-chat.view
  (:require [clojure.string :as string]
            [lui.elements :as elements]
            [lui.extension :as ext]
            [lui.macros :refer [defui reactive event host?]]
            [lui.protocol :as proto :refer [TextChanged]]
            [lui.ui :as ui]
            [logseq-chat.model :as model]
            [logseq-chat.view-base :as base]
            [logseq-chat.view-rows :as rows]
            [logseq-chat.view-sidebar :as sidebar]
            [logseq-chat.view-outliner :as outl]
            [logseq-chat.view-composer :as composer]
            [logseq-chat.view-flashcards :as cards]
            [logseq-chat.view-graphs :as graphsv]
            [logseq-chat.view-settings :as settings]
            [logseq-chat.view-screens :as screens]
            [signal.core :as signal]))

(type-alias retained-outline-row :rows/retained-row)

(def active-app-node-routes base/active-app-node-routes)
(def active-node-breadcrumbs base/active-node-breadcrumbs)
(def active-node-has-breadcrumbs? base/active-node-has-breadcrumbs?)
(def active-node-linked-reference-rows base/active-node-linked-reference-rows)
(def active-node-page-uuid base/active-node-page-uuid)
(def active-node-projection base/active-node-projection)
(def active-node-related-rows base/active-node-related-rows)
(def active-node-title base/active-node-title)
(def active-node-uuid base/active-node-uuid)
(def active-overflow-menu screens/active-overflow-menu)
(def active-page-actions-visible? base/active-page-actions-visible?)
(def active-page-favorite-label base/active-page-favorite-label)
(def active-route-only base/active-route-only)
(def active-search-node-routes base/active-search-node-routes)
(def add-first-block-button outl/add-first-block-button)
(def android-composer-send-button composer/android-composer-send-button)
(def app-navigation-depth base/app-navigation-depth)
(def apple-composer-send-button composer/apple-composer-send-button)
(def application-main-content screens/application-main-content)
(def application-shell-visible? base/application-shell-visible?)
(def authentication-content screens/authentication-content)
(def authentication-error-message base/authentication-error-message)
(def authentication-error-present? base/authentication-error-present?)
(def authentication-screen screens/authentication-screen)
(def authentication-screen-visible? base/authentication-screen-visible?)
(def authentication-signing-in? base/authentication-signing-in?)
(def block-search-results base/block-search-results)
(def block-search-results-present? base/block-search-results-present?)
(def bool-wire-value base/bool-wire-value)
(def bottom-chrome-capture-and-search? base/bottom-chrome-capture-and-search?)
(def bottom-chrome-editor? base/bottom-chrome-editor?)
(def bottom-chrome-expanded-composer? base/bottom-chrome-expanded-composer?)
(def bottom-chrome-occupies-layout-space? base/bottom-chrome-occupies-layout-space?)
(def bottom-chrome-presentation base/bottom-chrome-presentation)
(def bottom-chrome-selection? base/bottom-chrome-selection?)
(def breadcrumb-button outl/breadcrumb-button)
(def breadcrumb-identifier base/breadcrumb-identifier)
(def breadcrumb-title base/breadcrumb-title)
(def capture-and-search-row screens/capture-and-search-row)
(def chat-main-view screens/chat-main-view)
(def chat-view screens/chat-view)
(def collapsed-composer-button composer/collapsed-composer-button)
(def composer-asset-identifier base/composer-asset-identifier)
(def composer-asset-path base/composer-asset-path)
(def composer-asset-preview composer/composer-asset-preview)
(def composer-asset-title base/composer-asset-title)
(def composer-asset-view composer/composer-asset-view)
(def composer-assets-present? base/composer-assets-present?)
(def composer-attachment-button composer/composer-attachment-button)
(def composer-autofocus? base/composer-autofocus?)
(def composer-collapsed? base/composer-collapsed?)
(def composer-draft base/composer-draft)
(def composer-expanded? base/composer-expanded?)
(def composer-send-button composer/composer-send-button)
(def composer-send-disabled? base/composer-send-disabled?)
(def composer-task-status-button composer/composer-task-status-button)
(def composer-view composer/composer-view)
(def connection-control-visible? base/connection-control-visible?)
(def connection-settings-visible? base/connection-settings-visible?)
(def current-content-active? base/current-content-active?)
(def current-content-is-property? base/current-content-is-property?)
(def current-content-is-tag? base/current-content-is-tag?)
(def drawer-disabled? base/drawer-disabled?)
(def drawer-selected? base/drawer-selected?)
(def editing-caret base/editing-caret)
(def editing-title base/editing-title)
(def effect-error-message base/effect-error-message)
(def effect-error-present? base/effect-error-present?)
(def empty-graphs-loading? base/empty-graphs-loading?)
(def empty-graphs-refreshable? base/empty-graphs-refreshable?)
(def error-separator base/error-separator)
(def extension-int base/extension-int)
(def extension-string base/extension-string)
(def favorites-empty? base/favorites-empty?)
(def first-flashcard base/first-flashcard)
(def first-journal-retained-rows rows/first-journal-retained-rows)
(def first-journal-section-identifier rows/first-journal-section-identifier)
(def first-journal-section-visible? rows/first-journal-section-visible?)
(def flashcard-answer-identifier base/flashcard-answer-identifier)
(def flashcard-answer-row cards/flashcard-answer-row)
(def flashcard-answer-rows-visible? base/flashcard-answer-rows-visible?)
(def flashcard-answer-text base/flashcard-answer-text)
(def flashcard-question base/flashcard-question)
(def flashcard-rating-button cards/flashcard-rating-button)
(def flashcard-remaining-label base/flashcard-remaining-label)
(def flashcard-review-content cards/flashcard-review-content)
(def flashcard-screen cards/flashcard-screen)
(def flashcard-show-answer? base/flashcard-show-answer?)
(def flashcard-show-cloze? base/flashcard-show-cloze?)
(def flashcard-show-ratings? base/flashcard-show-ratings?)
(def flashcards-destination? base/flashcards-destination?)
(def flashcards-empty? base/flashcards-empty?)
(def flashcards-present? base/flashcards-present?)
(def flashcards-sidebar-selected? base/flashcards-sidebar-selected?)
(def flashcards-tab-visible? base/flashcards-tab-visible?)
(def flutter-app-root-visible? base/flutter-app-root-visible?)
(def flutter-graph-picker-catalog graphsv/flutter-graph-picker-catalog)
(def flutter-graph-picker-empty-state graphsv/flutter-graph-picker-empty-state)
(def flutter-graph-picker-loading-state graphsv/flutter-graph-picker-loading-state)
(def flutter-search-root-visible? base/flutter-search-root-visible?)
(def global-effect-error-feedback screens/global-effect-error-feedback)
(def global-effect-error-present? base/global-effect-error-present?)
(def graph-create-disabled? base/graph-create-disabled?)
(def graph-create-sheet graphsv/graph-create-sheet)
(def graph-delete-active? base/graph-delete-active?)
(def graph-delete-dialog graphsv/graph-delete-dialog)
(def graph-delete-identifier base/graph-delete-identifier)
(def graph-deletion-message base/graph-deletion-message)
(def graph-deletion-pending? base/graph-deletion-pending?)
(def graph-icon-name base/graph-icon-name)
(def graph-identifier base/graph-identifier)
(def graph-label base/graph-label)
(def graph-list-row graphsv/graph-list-row)
(def graph-loading-feedback screens/graph-loading-feedback)
(def graph-loading-message base/graph-loading-message)
(def graph-loading-visible? base/graph-loading-visible?)
(def graph-not-ready? base/graph-not-ready?)
(def graph-password-empty? base/graph-password-empty?)
(def graph-password-sheet graphsv/graph-password-sheet)
(def graph-picker-error-banner graphsv/graph-picker-error-banner)
(def graph-picker-error-code base/graph-picker-error-code)
(def graph-picker-error-message base/graph-picker-error-message)
(def graph-picker-error-present? base/graph-picker-error-present?)
(def graph-picker-error-reason base/graph-picker-error-reason)
(def graph-picker-error-title base/graph-picker-error-title)
(def graph-picker-hidden? base/graph-picker-hidden?)
(def graph-picker-overflow-menu graphsv/graph-picker-overflow-menu)
(def graph-picker-screen graphsv/graph-picker-screen)
(def graph-picker-screen-visible? base/graph-picker-screen-visible?)
(def graph-picker-visible? base/graph-picker-visible?)
(def graph-row graphsv/graph-row)
(def graph-row-disabled? base/graph-row-disabled?)
(def graph-row-local? base/graph-row-local?)
(def graph-selected? base/graph-selected?)
(def graph-status-identifier base/graph-status-identifier)
(def graph-status-title base/graph-status-title)
(def graph-status-visible? base/graph-status-visible?)
(def graph-title base/graph-title)
(def graph-unlock-disabled? base/graph-unlock-disabled?)
(def graph-unlock-error-message base/graph-unlock-error-message)
(def graph-unlock-error-present? base/graph-unlock-error-present?)
(def graphs-destination? base/graphs-destination?)
(def graphs-empty? base/graphs-empty?)
(def graphs-present? base/graphs-present?)
(def graphs-screen graphsv/graphs-screen)
(def graphs-sidebar-selected? base/graphs-sidebar-selected?)
(def graphs-tab-visible? base/graphs-tab-visible?)
(def handle-native-navigation-event base/handle-native-navigation-event)
(def handle-native-overflow-menu-event base/handle-native-overflow-menu-event)
(def handle-native-search-event base/handle-native-search-event)
(def handle-outliner-block-content-event base/handle-outliner-block-content-event)
(def handle-outliner-editor-event base/handle-outliner-editor-event)
(def int-wire-value base/int-wire-value)
(def journal-home-visible? base/journal-home-visible?)
(def journal-navigation-model base/journal-navigation-model)
(def journal-root-visible? base/journal-root-visible?)
(def journal-route-active? base/journal-route-active?)
(def journal-section-marker-for base/journal-section-marker-for)
(def journal-tree-panes screens/journal-tree-panes)
(def journal-tree-retained? base/journal-tree-retained?)
(def journals-destination? base/journals-destination?)
(def journals-sidebar-selected? base/journals-sidebar-selected?)
(def local-graphs base/local-graphs)
(def local-graphs-empty? base/local-graphs-empty?)
(def main-bottom-chrome screens/main-bottom-chrome)
(def main-can-add-first-block? base/main-can-add-first-block?)
(def main-header-connection screens/main-header-connection)
(def main-header-leading screens/main-header-leading)
(def main-header-sync screens/main-header-sync)
(def main-header-title screens/main-header-title)
(def main-linked-reference-section-visible? base/main-linked-reference-section-visible?)
(def main-related-section-visible? base/main-related-section-visible?)
(def main-screen-visible? base/main-screen-visible?)
(def main-tag-section-visible? base/main-tag-section-visible?)
(def main-title base/main-title)
(def make-retained-outline-row rows/make-retained-outline-row)
(def model-community-links base/model-community-links)
(def model-composer-assets base/model-composer-assets)
(def model-create-graph-open? base/model-create-graph-open?)
(def model-graph-menu-open? base/model-graph-menu-open?)
(def model-graph-password base/model-graph-password)
(def model-graph-password-open? base/model-graph-password-open?)
(def model-graphs base/model-graphs)
(def model-language-choices base/model-language-choices)
(def model-new-graph-encrypted? base/model-new-graph-encrypted?)
(def model-new-graph-name base/model-new-graph-name)
(def model-outliner-autocomplete-candidates base/model-outliner-autocomplete-candidates)
(def model-search-loading? base/model-search-loading?)
(def model-search-open? base/model-search-open?)
(def model-search-query base/model-search-query)
(def model-settings-appearance-menu-open? base/model-settings-appearance-menu-open?)
(def model-settings-language-menu-open? base/model-settings-language-menu-open?)
(def model-settings-open? base/model-settings-open?)
(def model-sync-details-open? base/model-sync-details-open?)
(def model-task-status-picker-open? base/model-task-status-picker-open?)
(def model-task-statuses base/model-task-statuses)
(def native-navigation-view screens/native-navigation-view)
(def native-node-screen screens/native-node-screen)
(def native-search-view screens/native-search-view)
(def navigation-path-depth base/navigation-path-depth)
(def new-graph-name-empty? base/new-graph-name-empty?)
(def node-breadcrumb-button outl/node-breadcrumb-button)
(def node-breadcrumbs outl/node-breadcrumbs)
(def node-can-add-first-block? base/node-can-add-first-block?)
(def node-linked-reference-section outl/node-linked-reference-section)
(def node-linked-reference-section-visible? base/node-linked-reference-section-visible?)
(def node-navigation-active? base/node-navigation-active?)
(def node-navigation-inactive? base/node-navigation-inactive?)
(def node-outliner-visible? base/node-outliner-visible?)
(def node-projection-identifier base/node-projection-identifier)
(def node-related-row outl/node-related-row)
(def node-related-section outl/node-related-section)
(def node-related-section-visible? base/node-related-section-visible?)
(def node-route-model base/node-route-model)
(def node-screen outl/node-screen)
(def node-screen-visible? base/node-screen-visible?)
(def node-tag-section-empty? base/node-tag-section-empty?)
(def node-tag-section-visible? base/node-tag-section-visible?)
(def node-tagged-section outl/node-tagged-section)
(def node-title-visible? base/node-title-visible?)
(def older-journals-visible? base/older-journals-visible?)
(def optional-string base/optional-string)
(def outliner-autocomplete-active? base/outliner-autocomplete-active?)
(def outliner-autocomplete-bar outl/outliner-autocomplete-bar)
(def outliner-autocomplete-identifier base/outliner-autocomplete-identifier)
(def outliner-autocomplete-label base/outliner-autocomplete-label)
(def outliner-autocomplete-row outl/outliner-autocomplete-row)
(def outliner-collapse-button outl/outliner-collapse-button)
(def outliner-collapse-icon-name base/outliner-collapse-icon-name)
(def outliner-collapse-identifier base/outliner-collapse-identifier)
(def outliner-editor-active? base/outliner-editor-active?)
(def outliner-editor-task-label base/outliner-editor-task-label)
(def outliner-editor-toolbar outl/outliner-editor-toolbar)
(def outliner-editor-view outl/outliner-editor-view)
(def outliner-entry outl/outliner-entry)
(def outliner-first-journal-section outl/outliner-first-journal-section)
(def outliner-indent-view outl/outliner-indent-view)
(def outliner-journal-accessibility-label base/outliner-journal-accessibility-label)
(def outliner-journal-button-identifier base/outliner-journal-button-identifier)
(def outliner-journal-divider-visible? base/outliner-journal-divider-visible?)
(def outliner-journal-heading-visible? base/outliner-journal-heading-visible?)
(def outliner-journal-marker base/outliner-journal-marker)
(def outliner-journal-page-id base/outliner-journal-page-id)
(def outliner-journal-title base/outliner-journal-title)
(def outliner-rich-block-view outl/outliner-rich-block-view)
(def outliner-row outl/outliner-row)
(def outliner-row-action-identifier base/outliner-row-action-identifier)
(def outliner-row-action-label base/outliner-row-action-label)
(def outliner-row-asset-type base/outliner-row-asset-type)
(def outliner-row-breadcrumb base/outliner-row-breadcrumb)
(def outliner-row-breadcrumbs base/outliner-row-breadcrumbs)
(def outliner-row-collapse-glyph base/outliner-row-collapse-glyph)
(def outliner-row-collapse-label base/outliner-row-collapse-label)
(def outliner-row-completed-wire-value base/outliner-row-completed-wire-value)
(def outliner-row-completed? base/outliner-row-completed?)
(def outliner-row-content outl/outliner-row-content)
(def outliner-row-fallback-breadcrumb? base/outliner-row-fallback-breadcrumb?)
(def outliner-row-has-breadcrumb? base/outliner-row-has-breadcrumb?)
(def outliner-row-has-children base/outliner-row-has-children)
(def outliner-row-has-status? base/outliner-row-has-status?)
(def outliner-row-has-tags? base/outliner-row-has-tags?)
(def outliner-row-id-wire-value base/outliner-row-id-wire-value)
(def outliner-row-identifier base/outliner-row-identifier)
(def outliner-row-indent base/outliner-row-indent)
(def outliner-row-journal? base/outliner-row-journal?)
(def outliner-row-list-item-press-enabled? base/outliner-row-list-item-press-enabled?)
(def outliner-row-local-path base/outliner-row-local-path)
(def outliner-row-main-content outl/outliner-row-main-content)
(def outliner-row-status-title base/outliner-row-status-title)
(def outliner-row-structured-breadcrumb? base/outliner-row-structured-breadcrumb?)
(def outliner-row-sync-failed? base/outliner-row-sync-failed?)
(def outliner-row-tags base/outliner-row-tags)
(def outliner-row-title base/outliner-row-title)
(def outliner-row-uuid base/outliner-row-uuid)
(def outliner-row-youtube-target base/outliner-row-youtube-target)
(def outliner-row-zoom-identifier base/outliner-row-zoom-identifier)
(def outliner-row-zoom-label base/outliner-row-zoom-label)
(def outliner-selection-active? base/outliner-selection-active?)
(def outliner-selection-inactive? base/outliner-selection-inactive?)
(def outliner-selection-toolbar outl/outliner-selection-toolbar)
(def outliner-status-control outl/outliner-status-control)
(def outliner-tag outl/outliner-tag)
(def outliner-tag-identifier base/outliner-tag-identifier)
(def outliner-tag-title base/outliner-tag-title)
(def outliner-task-status-backlog? base/outliner-task-status-backlog?)
(def outliner-task-status-canceled? base/outliner-task-status-canceled?)
(def outliner-task-status-doing? base/outliner-task-status-doing?)
(def outliner-task-status-done? base/outliner-task-status-done?)
(def outliner-task-status-icon base/outliner-task-status-icon)
(def outliner-task-status-option-identifier base/outliner-task-status-option-identifier)
(def outliner-task-status-review? base/outliner-task-status-review?)
(def outliner-task-status-row composer/outliner-task-status-row)
(def outliner-task-status-style-is? base/outliner-task-status-style-is?)
(def outliner-task-status-todo? base/outliner-task-status-todo?)
(def outliner-zoom-control outl/outliner-zoom-control)
(def page-delete-dialog settings/page-delete-dialog)
(def page-deletion-pending? base/page-deletion-pending?)
(def page-search-results base/page-search-results)
(def page-search-results-present? base/page-search-results-present?)
(def primary-sidebar-button-visible? base/primary-sidebar-button-visible?)
(def recent-pages-empty? base/recent-pages-empty?)
(def related-row-breadcrumbs outl/related-row-breadcrumbs)
(def related-section-heading outl/related-section-heading)
(def remaining-retained-outliner-rows rows/remaining-retained-outliner-rows)
(def remote-graphs base/remote-graphs)
(def remote-graphs-present? base/remote-graphs-present?)
(def request-node-action base/request-node-action)
(def retained-journal-pane screens/retained-journal-pane)
(def retained-outliner-rows rows/retained-outliner-rows)
(def retained-row-editing-caret rows/retained-row-editing-caret)
(def retained-row-editing-title rows/retained-row-editing-title)
(def retained-row-editing? rows/retained-row-editing?)
(def retained-row-identifier rows/retained-row-identifier)
(def retained-row-value rows/retained-row-value)
(def root-outliner-view screens/root-outliner-view)
(def row-editing? base/row-editing?)
(def row-not-editing? base/row-not-editing?)
(def row-selected? base/row-selected?)
(def runtime-log-actions settings/runtime-log-actions)
(def runtime-log-empty? base/runtime-log-empty?)
(def runtime-log-error? base/runtime-log-error?)
(def runtime-log-errors-label base/runtime-log-errors-label)
(def runtime-log-level base/runtime-log-level)
(def runtime-log-message base/runtime-log-message)
(def runtime-log-order-label base/runtime-log-order-label)
(def runtime-log-record-identifier base/runtime-log-record-identifier)
(def runtime-log-records base/runtime-log-records)
(def runtime-log-row settings/runtime-log-row)
(def runtime-log-screen settings/runtime-log-screen)
(def runtime-log-sheet settings/runtime-log-sheet)
(def runtime-log-source-label base/runtime-log-source-label)
(def runtime-log-timestamp base/runtime-log-timestamp)
(def runtime-log-toolbar settings/runtime-log-toolbar)
(def runtime-log-visible? base/runtime-log-visible?)
(def search-empty-message base/search-empty-message)
(def search-empty-state-present? base/search-empty-state-present?)
(def search-empty-supporting-message base/search-empty-supporting-message)
(def search-navigation-depth base/search-navigation-depth)
(def search-node-routes base/search-node-routes)
(def search-query-present? base/search-query-present?)
(def search-result-breadcrumb base/search-result-breadcrumb)
(def search-result-context-present? base/search-result-context-present?)
(def search-result-identifier base/search-result-identifier)
(def search-result-row screens/search-result-row)
(def search-result-status base/search-result-status)
(def search-result-title base/search-result-title)
(def search-results-present? base/search-results-present?)
(def search-screen screens/search-screen)
(def selected-graph-local? base/selected-graph-local?)
(def selected-page-absent? base/selected-page-absent?)
(def selected-page-content-title-visible? base/selected-page-content-title-visible?)
(def selected-page-model-key base/selected-page-model-key)
(def selected-page-models base/selected-page-models)
(def selected-page-present? base/selected-page-present?)
(def selected-page-title base/selected-page-title)
(def selected-page-visible? base/selected-page-visible?)
(def settings-appearance-control settings/settings-appearance-control)
(def settings-appearance-title base/settings-appearance-title)
(def settings-apply-disabled? base/settings-apply-disabled?)
(def settings-auto-correction base/settings-auto-correction)
(def settings-available-tabs-present? base/settings-available-tabs-present?)
(def settings-base-url base/settings-base-url)
(def settings-base-url-invalid? base/settings-base-url-invalid?)
(def settings-community-link-identifier base/settings-community-link-identifier)
(def settings-community-link-needs-separator? base/settings-community-link-needs-separator?)
(def settings-community-link-row settings/settings-community-link-row)
(def settings-community-link-title base/settings-community-link-title)
(def settings-editor-card settings/settings-editor-card)
(def settings-export-row settings/settings-export-row)
(def settings-flashcards-after-graphs? base/settings-flashcards-after-graphs?)
(def settings-flashcards-before-graphs? base/settings-flashcards-before-graphs?)
(def settings-general-card settings/settings-general-card)
(def settings-language-choice-identifier base/settings-language-choice-identifier)
(def settings-language-choice-menu-item settings/settings-language-choice-menu-item)
(def settings-language-choice-radio settings/settings-language-choice-radio)
(def settings-language-choice-title base/settings-language-choice-title)
(def settings-language-control settings/settings-language-control)
(def settings-language-title base/settings-language-title)
(def settings-main-sheet settings/settings-main-sheet)
(def settings-main-visible? base/settings-main-visible?)
(def settings-revision base/settings-revision)
(def settings-runtime-log-row settings/settings-runtime-log-row)
(def settings-screen settings/settings-screen)
(def settings-sheet settings/settings-sheet)
(def settings-sign-out-row settings/settings-sign-out-row)
(def settings-spell-check base/settings-spell-check)
(def settings-tab-row settings/settings-tab-row)
(def settings-tab-title base/settings-tab-title)
(def settings-tabs-screen settings/settings-tabs-screen)
(def settings-tabs-sheet settings/settings-tabs-sheet)
(def settings-tabs-summary base/settings-tabs-summary)
(def settings-tabs-visible? base/settings-tabs-visible?)
(def settings-toggle-auto-correction settings/settings-toggle-auto-correction)
(def settings-toggle-spell-check settings/settings-toggle-spell-check)
(def settings-version base/settings-version)
(def sidebar-drag-disabled? base/sidebar-drag-disabled?)
(def sidebar-empty-section-label sidebar/sidebar-empty-section-label)
(def sidebar-favorites base/sidebar-favorites)
(def sidebar-flashcards-row sidebar/sidebar-flashcards-row)
(def sidebar-graph-disabled? base/sidebar-graph-disabled?)
(def sidebar-graph-identifier base/sidebar-graph-identifier)
(def sidebar-graph-menu-item sidebar/sidebar-graph-menu-item)
(def sidebar-graph-selected? base/sidebar-graph-selected?)
(def sidebar-graph-switch sidebar/sidebar-graph-switch)
(def sidebar-graph-switch-content sidebar/sidebar-graph-switch-content)
(def sidebar-graphs-row sidebar/sidebar-graphs-row)
(def sidebar-journals-row sidebar/sidebar-journals-row)
(def sidebar-page-identifier base/sidebar-page-identifier)
(def sidebar-page-row sidebar/sidebar-page-row)
(def sidebar-page-selected? base/sidebar-page-selected?)
(def sidebar-page-title base/sidebar-page-title)
(def sidebar-recent-pages base/sidebar-recent-pages)
(def sidebar-section-heading sidebar/sidebar-section-heading)
(def sidebar-tab-visible? base/sidebar-tab-visible?)
(def sidebar-view sidebar/sidebar-view)
(def string-vector-contains? base/string-vector-contains?)
(def string-wire-value base/string-wire-value)
(def sync-accessibility-identifier base/sync-accessibility-identifier)
(def sync-connection-label base/sync-connection-label)
(def sync-cursor-label base/sync-cursor-label)
(def sync-error-message base/sync-error-message)
(def sync-error-present? base/sync-error-present?)
(def sync-indicator-foreground base/sync-indicator-foreground)
(def sync-indicator-label base/sync-indicator-label)
(def sync-label base/sync-label)
(def sync-pending-label base/sync-pending-label)
(def sync-status-sheet settings/sync-status-sheet)
(def tab-disabled? base/tab-disabled?)
(def tab-down-identifier base/tab-down-identifier)
(def tab-enabled? base/tab-enabled?)
(def tab-index base/tab-index)
(def tab-move-down-disabled? base/tab-move-down-disabled?)
(def tab-move-up-disabled? base/tab-move-up-disabled?)
(def tab-movement-visible? base/tab-movement-visible?)
(def tab-selection-foreground base/tab-selection-foreground)
(def tab-selection-glyph base/tab-selection-glyph)
(def tab-selection-icon-name base/tab-selection-icon-name)
(def tab-toggle-identifier base/tab-toggle-identifier)
(def tab-toggle-label base/tab-toggle-label)
(def tab-up-identifier base/tab-up-identifier)
(def task-status-foreground base/task-status-foreground)
(def task-status-icon-name base/task-status-icon-name)
(def task-status-identifier base/task-status-identifier)
(def task-status-picker-dialog composer/task-status-picker-dialog)
(def task-status-row composer/task-status-row)
(def task-status-selected? base/task-status-selected?)
(def task-status-style base/task-status-style)
(def task-status-title base/task-status-title)
(def visible-flashcard-answer-rows base/visible-flashcard-answer-rows)

(defn composer-asset-schema []
  (ext/component "composer-asset"
   [(proto/profile proto/IOS proto/SwiftUIHost)]
   false []
   [(ext/property "title" ext/StringScalar true None)
    (ext/property "local-path" ext/StringScalar true None)] []))

(defn outliner-editor-schema []
  (ext/component
   "outliner-editor"
   [(proto/profile proto/IOS proto/SwiftUIHost)
    (proto/profile proto/AndroidOS proto/FlutterHost)]
   false []
   [(ext/property "block-id" ext/StringScalar true None)
    (ext/property "title" ext/StringScalar true None)
    (ext/property "caret-utf16-offset" ext/IntScalar true None)]
   [(ext/event
     "text-change"
     [(ext/event-field "title" ext/StringScalar true)
      (ext/event-field "caret-utf16-offset" ext/IntScalar true)])
    (ext/event
     "return"
     [(ext/event-field "title" ext/StringScalar true)
      (ext/event-field "caret-utf16-offset" ext/IntScalar true)])
    (ext/event
     "backspace"
     [(ext/event-field "title" ext/StringScalar true)
      (ext/event-field "selection-length" ext/IntScalar true)])
    (ext/event
     "caret-change"
     [(ext/event-field "caret-utf16-offset" ext/IntScalar true)])]))

(defn outliner-block-content-schema []
  (ext/component
   "outliner-block-content"
   [(proto/profile proto/IOS proto/SwiftUIHost)
    (proto/profile proto/AndroidOS proto/FlutterHost)]
   false []
   [(ext/property "title" ext/StringScalar true None)
    (ext/property "block-id" ext/StringScalar true None)
    (ext/property "markup-json" ext/StringScalar true None)
    (ext/property "youtube-target-url" ext/StringScalar true None)
    (ext/property "is-asset" ext/BoolScalar true None)
    (ext/property "is-completed" ext/BoolScalar true None)
    (ext/property "asset-type" ext/StringScalar true None)
    (ext/property "local-path" ext/StringScalar true None)]
   [(ext/event
     "drag-start"
     [(ext/event-field "uuid" ext/StringScalar true)])
    (ext/event
     "drop"
     [(ext/event-field "uuid" ext/StringScalar true)
      (ext/event-field "placement" ext/StringScalar true)])
    (ext/event
     "edit"
     [(ext/event-field "uuid" ext/StringScalar true)])
    (ext/event
     "open-node"
     [(ext/event-field "uuid" ext/StringScalar true)])]))

(defn native-navigation-stack-schema []
  (ext/component
   "native-navigation-stack"
   [(proto/profile proto/IOS proto/SwiftUIHost)
    (proto/profile proto/AndroidOS proto/FlutterHost)]
   true []
   [(ext/property "depth" ext/IntScalar true None)
    (ext/property "bottom-occupies-layout-space" ext/BoolScalar true None)
    (ext/property "composer-dismissal-enabled" ext/BoolScalar true None)
    (ext/property "title" ext/StringScalar true None)]
   [(ext/event "back" [(ext/event-field "count" ext/IntScalar true)])
    (ext/event "dismiss-composer" [])]))

(defn native-search-presentation-schema []
  (ext/component
   "native-search-presentation"
   [(proto/profile proto/IOS proto/SwiftUIHost)
    (proto/profile proto/AndroidOS proto/FlutterHost)]
   true []
   [(ext/property "presented" ext/BoolScalar true None)
    (ext/property "depth" ext/IntScalar true None)
    (ext/property "query" ext/StringScalar true None)
    (ext/property "title" ext/StringScalar true None)]
   [(ext/event "back" [(ext/event-field "count" ext/IntScalar true)])
    (ext/event "dismiss" [])
    (ext/event
     "query-changed"
     [(ext/event-field "query" ext/StringScalar true)])]))

(defn native-overflow-menu-schema []
  (ext/component
   "native-overflow-menu"
   [(proto/profile proto/IOS proto/SwiftUIHost)
    (proto/profile proto/AndroidOS proto/FlutterHost)]
   false []
   [(ext/property "page-actions-visible" ext/BoolScalar true None)
    (ext/property "favorite-label" ext/StringScalar true None)
    (ext/property "settings-visible" ext/BoolScalar true None)]
   [(ext/event "favorite" [])
    (ext/event "share" [])
    (ext/event "delete" [])
    (ext/event "settings" [])]))

(defn liquid-glass-schema []
  (ext/tweak
   "liquid-glass"
   [(proto/profile proto/IOS proto/SwiftUIHost)]
   [(ext/property "shape" ext/StringScalar true None)]))

(defn extension-registry []
  (let [registry (ext/registry)]
    (ext/register-component! registry (outliner-editor-schema))
    (ext/register-component! registry (outliner-block-content-schema))
    (ext/register-component! registry (composer-asset-schema))
    (ext/register-component! registry (native-navigation-stack-schema))
    (ext/register-component! registry (native-search-presentation-schema))
    (ext/register-component! registry (native-overflow-menu-schema))
    (ext/register-tweak! registry (liquid-glass-schema))
    registry))
